FROM php:7.4-apache

ENV APACHE_DOCUMENT_ROOT = /var/www/html

COPY src/ /var/www/html/

WORKDIR /var/www/html/

RUN a2enmod rewrite
RUN service apache2 restart

CMD ["apache2ctl", "-D", "FOREGROUND"]